import { UserDBType } from './UserDBProvider.types';

export const DEFAULT_CREATE_USER_DB: Omit<UserDBType, 'id'> = {
  cognitoId: '',
  email: '',
  firstName: '',
  displayName: null,
  diagnosisYear: null,
  description: null,
  designation: null,
  role: null,
  lastName: null,
  phoneNumber: null,
  dob: null,
  addressLine1: null,
  addressLine2: null,
  city: null,
  state: null,
  country: null,
  zipCode: null,
  diagnosisTypes: null,
  diagnosisSubTypes: null,
  age: null,
  gender: null,
  diagnosisDate: null,
  timeline: null,
  phoneNumberLocation: null,
  profilePicture: null,
  config: null,
};
