-- SUPERSEDED / APPLIED 2026-08-05.
-- This design was applied to the Laurie's Love project (iwbfsbriippzmdyrsmsu)
-- and then RECONCILED with Jeremy's existing support_staff / support_tickets
-- tables, which already existed on the DB.
--
-- What changed from this original proposal:
--   * staff_roles (this file's staff table) was DROPPED — Jeremy's
--     support_staff (roles: owner | agent) is the single staff source of truth.
--   * is_admin()/is_staff() now read support_staff (owner = admin).
--   * support_tickets / support_ticket_messages here were NOT created — Jeremy's
--     support_tickets (user_id / category / description / conversation_id)
--     already exists and is populated.
--   * KEPT (net-new, no conflict): organizations, platform_features
--     (feature-toggle / licensing layer), moderation_queue.
--
-- The applied, reconciled end state lives in:
--   supabase/migrations/20260805173233_admin_foundation_core_v1.sql
--
-- This file is retained only as a record of the original proposal. Do not run.
