name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: laurieslove-api
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: laurieslove-api
          IMAGE_TAG: latest
        run: |
          CURRENT_SHA=${GITHUB_SHA::8}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:${CURRENT_SHA}

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: laurieslove-api
          IMAGE_TAG: latest
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Restart ECS Cluster
        env:
          CLUSTER_NAME: laurieslove-api
          SERVICE_NAME: laurieslove-api-service-production
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
  sentry:
    name: Deploy to Sentry
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      
      - name: Build and Install Dependencies
        run: npm install && npm run build

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Inject and Upload Sentry Source Maps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: your-sentry-org
          SENTRY_PROJECT: laurieslove-api
        run: |
          sentry-cli sourcemaps inject --org $SENTRY_ORG --project $SENTRY_PROJECT ./dist
          sentry-cli sourcemaps upload --org $SENTRY_ORG --project $SENTRY_PROJECT ./dist

      - name: Set up Sentry Release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: your-sentry-org
          SENTRY_PROJECT: laurieslove-api
        run: |
          sentry-cli releases new "$GITHUB_SHA"
          sentry-cli releases set-commits --auto "$GITHUB_SHA"
  
      - name: Notify Sentry Deployment
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: your-sentry-org
          SENTRY_PROJECT: laurieslove-api
        run: |
          sentry-cli releases deploys "$GITHUB_SHA" new -e production